spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/Test}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:Root}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
springdoc:
  pathsToMatch: /api/**
server:
  port: 8081
